### ISSUE TITLE
Create Landing Page & Contract Overview Page

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/allo-scan#20]
Contract Overview

Like in our Example. We should add the headline "Core Contracts", "Contract Overview" or similar
![Image](https://github.com/allo-protocol/allo-scan/assets/22886639/73ffb32b-7e0e-4e14-8be4-ea80973a42da)

**Comment by 0xKurt** [comment]
also we should add cloneable strategies

**Comment by codenamejason** [comment]
![Image](https://github.com/allo-protocol/allo-scan/assets/9419140/dcc4353d-4c03-4c2b-8b3f-a6193781b06e)
