### ISSUE TITLE
Create Landing Page: Master Table

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/allo-scan#21]
_Note:_ Depending on available time in appetite

Requires: Master table on spec to populate the overview page

Section should contain a headline and a table with the following attributes:

- Txn Hash
- Contract
- msg.sender
- timestamp
- function invoked
- link to block explorer

**Comment by thelostone-mc** [comment]
https://github.com/allo-protocol/allo-scan/pull/47
